events {}

http {
    limit_req_zone $binary_remote_addr zone=api_limit:10m rate=5r/s; # Also including rate limiting in this
    proxy_cache_path /var/cache/nginx keys_zone=my_cache:10m max_size=1g inactive=60m;

    upstream victims {
        server victim_1:9000;
        server victim_2:9000;
        server victim_3:9000;
    }

    server {
        listen 9000;
        location / {
            limit_req zone=api_limit burst=10 nodelay;
            limit_req_status 429;

            proxy_cache my_cache;
            add_header X-Cache-Status $upstream_cache_status;

            proxy_pass http://victims;

            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }
    }
}