services:
  victim:
    build:
      context: ../../victim
    container_name: victim
    ports:
      - "9000:9000"
    
    networks:
      - victim_network

    deploy:
      resources:
        limits:
          cpus: "0.25"
          memory: 128M
          pids: 64

    mem_limit: 128m
    cpus: 0.25

networks:
  victim_network:
    name: victim_network
    driver: bridge
    ipam:
      config:
        - subnet: 192.0.2.0/24