events {}

http {
	proxy_cache_path /var/cache/nginx # store cache
		keys_zone=my_cache:10m    # memory allocated to the table of entry for <cache_key, response>
		max_size=1g               # max cache response size
		inactive=60m              # sets a timer before removing cache response >60

	upstream victim { server victim:9000; }

	server {
		listen 9000;
		
		# Forwards cache to victim using table 'my_cache' and tracks each requests
		location / {
			proxy_cache my_cache;
			proxy_pass http://victim;

			add_header X-Cache-Status $upstream_cache_status; # track HIT/MISS requests
		}
	}
}
