events {}

http {
	# Creates table to store cache and sets rules (size, memory allocated and time to live)
	proxy_cache_path /var/cache/nginx 
		keys_zone=my_cache:10m
		max_size=1g
		inactive=60m;

	upstream victim { server victim:9000; }

	server {
		listen 9000;
		
		# Forwards cache to victim using table 'my_cache' and tracks each requests
		location / {
			proxy_cache my_cache;
			proxy_pass http://victim;

			# track HIT/MISS requests
			add_header X-Cache-Status $upstream_cache_status;
		}
	}
}
