# PS: Forgot to add Instance but that's just details

services:
  victim_1:
    build:
      context: ../../victim

    container_name: victim_1
    networks:
      - victim_network

    mem_limit: 128m
    cpus: 0.25
    pids_limit: 64

  victim_2:
    build:
      context: ../../victim

    container_name: victim_2
    networks:
      - victim_network

    mem_limit: 128m
    cpus: 0.25
    pids_limit: 64

  victim_3:
    build:
      context: ../../victim

    container_name: victim_3
    networks:
      - victim_network

    mem_limit: 128m
    cpus: 0.25
    pids_limit: 64

  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "9000:9000" # NGINX exposes the port rather than HTTP server itself

    volumes:
      - ../../fixes/load_balancing/nginx.conf:/etc/nginx/nginx.conf:ro

    depends_on:
      - victim_1
      - victim_2
      - victim_3

    networks:
      - victim_network

networks:
  victim_network:
    name: victim_network
    driver: bridge

    ipam:
      config:
        - subnet: 192.0.2.0/24